name: Node.js CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - run: pnpm --version
      - run: which pnpm

      - run: pnpm run lint
      - run: pnpm test
      - run: pnpm run coverage -- --coverage
